version: "3.9"
networks:
  kong-net:
    name: kong-net
services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    restart: on-failure
    networks:
      - kong-net
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass

  kong-gateway:
    image: kong/kong-gateway:3.2.2.1
    container_name: kong-gateway
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - kong-net
    depends_on:
      - kong-database
  konga:
    image: pantsel/konga
    container_name: konga
    restart: on-failure
    networks:
      - kong-net
    ports:
      - "1337:1337"
    depends_on:
      - kong-gateway
      # http://kong-gateway:8001
      # host.docker.internal or localhost or service name
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: on-failure
    # --path.rootfs=/host
    # --path.procfs=/host/proc
    # --path.sysfs=/host/sys
    command:
      - '--path.rootfs=/host'
    # volumes:
    #   - /:/host:ro,rslave
    networks:
      - kong-net
    ports:
      - "9100:9100"
    depends_on:
      - kong-gateway

  prometheus:
    image: prom/prometheus:latest
    networks:
      - kong-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - kong-gateway
      - node-exporter
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - kong-net
    ports:
      - "3000:3000"
    depends_on:
      - kong-gateway
      - prometheus 
      # 1860
    volumes:
      - ./grafana-storage:/var/lib/grafana
