global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  #- "first_rule.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'kong-metrics'
    static_configs:
    - targets: ['kong-gateway:8001']